# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

sudo: required

python:
  - 2.7
  - 3.5

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
#  - sudo apt-get update
#  - sudo apt-get install vtk6
#  - sudo apt-get install tcl-vtk
#  - sudo apt-get install libvtk6
#  - sudo apt-get install libvtk6-dev
#  - sudo apt-get install python-vtk
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install nose>=1.3.7 coverage codecov pytest>=3.0.5

before_script:
  - python setup.py build_ext --inplace
  - mkdir output

script:
  - nosetests -v --exe --with-doctest --with-xunit --with-coverage --cover-package=morphsnakes
  - codecov

after_success:
  - codecov -t dd9e3be7-daad-44a6-871c-17d061159fe1
  - coverage report
